### ISSUE TITLE
Restore coverage

### ISSUE THREAD

**Issue by frank06** [flutterdata/flutter_data#270]
```
- name: Generate coverage
        if: runner.os == 'macOS'
        run: dart run coverage:test_with_coverage
      - name: Send coverage report to codecov
        if: runner.os == 'macOS'
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
```
